### PR TITLE
Update CAN.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Add beta warning because CAN is still experimental

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
@sg- please verify. I suggested this change based on my understanding of the CAN driver being unsupported.

**Comment by sg-** [comment]
I wouldnt suggest its experimental or in beta. Its been around since 2009ish

**Comment by BlackstoneEngineering** [comment]
Ok, then my understanding is incorrect. I just went back an looked at mbed-os and it looks like can is not in features/unsupported like I thought it was, my bad. Will work on getting the CAN API page in the docs up to date, cause it looks like something got dropped in transition.

@AnotherButler my bad, lets talk about this monday? Lets work with @mbartling to verify the CAN API and get the API page updated.

**Comment by AnotherButler** [comment]
@BlackstoneEngineering Sounds good. I'm going to close this PR as it's incorrect.

**Comment by BlackstoneEngineering** [comment]
Cool, can you please work with michael to get the CAN API page updated to reflect its actual API and relevant examples?

**Pull request closed without merging**
