### PR TITLE
mbed OS 5.5 Cellular API docs

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Basic use and porting documentation for cellular APIs being introduced in mbed OS 5.5

Bulk of this written by @hasnainvirk, I just tidied and expanded.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
FYI @TuomoHautamaki, @SeppoTakalo, @sg-, @peknis01

**Comment by hasnainvirk** [comment]
@kjbracey-arm I have added some more stuff to the docs and opened a new PR here https://github.com/ARMmbed/mbed_OS_API_Docs/pull/82.
Also I squashed various commits into 1. I couldn't push to your fork because of permissions, so I had to make a new PR.

**Comment by AnotherButler** [comment]
Shall I close this in favor of #82 ?

**Comment by AnotherButler** [comment]
Closing in favor of #82 Please reopen if necessary

**Pull request closed without merging**
