### PR TITLE
Update NSAPI return codes

### PR DESCRIPTION
**Pull request by sarahmarshy**
The error codes in the current doc are outdated. This was pointed out in a developer site question - https://developer.mbed.org/questions/78652/mbed-5-network-sockets-return-code-3012/#answer13100. The current valid return codes can be found in [this file](https://github.com/ARMmbed/mbed-os/blob/master/features/netsocket/nsapi_types.h#L37).

@AnotherButler

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]
Great catch. Thanks @sarahmarshy

**Comment by AnotherButler** [comment]
Before I merge - I see this is for 5.3. Does this also need to be changed for 5.4 and 5.5?

**Comment by sarahmarshy** [comment]
@AnotherButler I would think so. Sorry, I didn't realize which branch I was committing on!

**Comment by AnotherButler** [comment]
I've updated the readme for this repo, as well as for the handbook, so it shouldn't be so confusing anymore. Thanks @sarahmarshy

**Pull request closed without merging**
