### PR TITLE
Add more mbed-events documentation

### PR DESCRIPTION
**Pull request by geky**
More events docs!

- events_usage.md
- events_design.md

I didn't add these to the index for the tasks directory (references
rtos/timer/events), but just added references from the main events.md
page.

Looking forward to review
cc @AnotherButler

### CODE REVIEW

**Comment by sg-** [comment]
This needs wider review for positioning

**Comment by AnotherButler** [comment]
@sg- We are considering turning the events_design page into a blog post. Should we hold off?

**Comment by sg-** [comment]
please do.

**Comment by sg-** [comment]
I mean, write it but jan already did one so we'll need to review it

**Pull request closed without merging**
